### ISSUE TITLE
Please check the description for RcppMLPACK

### ISSUE THREAD

**Issue by anshabhi** [rstats-gsoc/gsoc2019#1]
Hello,

Can you please verify if the description for [RcppMLPACK]( https://github.com/rstats-gsoc/gsoc2019/wiki/RcppMLPACK) is correct?

Thanks!
Abhinav

**Comment by abernauer** [comment]
Just a heads up it's the same as the template on the project description table.

**Comment by mrabhinavagarwal** [comment]
RCPPMLPACK description has been updated
